services:
  app:
    build:
      context: .
    image: sticky-iky
    container_name: sticky-iky
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    develop:
      watch:
        - action: sync
          path: ./
          target: ./
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
